### ISSUE TITLE
在docker swarm中使用webman 进程错误不能触发services重启 

### ISSUE THREAD

**Issue by Iamzz-cn** [walkor/webman#30]
如果其中一个进程死了,没有触发docker的重启
docker-compose.yml
```
version: "3"
services:
  http:
...
    deploy:
      replicas: 2
      restart_policy:
        condition: always
...
    networks:
      - test
networks:
  test:
```
Dockerfile
```
...
CMD ["php","-d","memory_limit=512M","start.php","start"]
```
